<?php

// 0 - notify user that your password is changed
// 1 - to send reset password OTP
// 2 - to send sign-up OTP email
// 3 - to send Thank you Email for sign-up
// 4 - to send Email when user fill contact form (notify that we will get back to you.)
// 5 - Admin - send Email to admin that user filled contact form (notify that connect with customer.)

//! to notify user that your password is changed - Email
$template[0] = "<div marginheight='0' marginwidth='0' style='width:100%!important;margin:0;padding:0'>
<span style='border:none;padding:0;margin:0;display:none;font-size:1px'></span><table style='border-collapse:collapse;padding:0;max-width:480px;width:100%;border:0;background-color:#ffffff;margin:0 auto;word-break:break-word;' cellpadding='0' cellspacing='0'><tbody style='border:none;padding:0;margin:0'><tr style='border:none;margin:0px;padding:0px'><td style='border:none;padding:0;margin:0'>
<div id='m_-6477240843616158778m_2370322099211961721main' style='border:none;padding:0;margin:0'><table style='border-collapse:collapse;padding:0;background-color:#ffffff;text-align:left;width:100%;height:50px'><tbody style='border:none;padding:0;margin:0'><tr style='border:none;margin:0px;padding:0px;height:24px'><td colspan='3' style='border:none;padding:0;margin:0;height:24px'></td></tr><tr style='border:none;margin:0px;padding:0px'><td style='border:none;padding:0;margin:0;width:24px'></td><td style='border:none;padding:0;margin:0'>
<a href='https://visionizex.tech/images/logo/logo.png' style='text-decoration:none;color:#1ed760' rel='noreferrer' target='_blank' data-saferedirecturl='https://visionizex.tech/images/logo/logo.png'><img alt='' style='display:block;max-width:100%;margin-right:auto;width:75px;height:60px' height='37' src='https://visionizex.tech/images/logo/logo.png' class='CToWUd' data-bit='iit'></a></td><td style='border:none;padding:0;margin:0;width:24px'></td></tr><tr style='border:none;margin:0px;padding:0px;height:24px'><td colspan='3' style='border:none;padding:0;margin:0;height:24px'></td></tr></tbody></table><table style='border-collapse:collapse;padding:0;width:100%;background-color:#ffffff font-family:&quot;helvetica&quot;,&quot;arial&quot;,sans-serif!important;font-size:48px' dir='auto'><tbody style='border:none;padding:0;margin:0'><tr style='border:none;margin:0px;padding:0px;height:24px'><td colspan='3' style='border:none;padding:0;margin:0;height:24px'></td></tr><tr style='border:none;margin:0px;padding:0px'><td style='border:none;padding:0;margin:0;width:24px'></td><td style='border:none;padding:0;margin:0'><p style='border:none;padding:0;margin:0;background-color:#ffffff;color:#000000;font-size:48px;font-family:&quot;helvetica&quot;,&quot;arial&quot;,sans-serif!important;font-weight:400;text-align:left'>
<b style='border:none;padding:0;margin:0'>Your password has been changed.<b style='border:none;padding:0;margin:0'></b></b></p></td><td style='border:none;padding:0;margin:0;width:24px'></td></tr><tr style='border:none;margin:0px;padding:0px;height:16px'><td colspan='3' style='border:none;padding:0;margin:0;height:16px'></td></tr></tbody></table><table style='border-collapse:collapse;padding:0;width:100%;background-color:#ffffff;font-family:&quot;helvetica&quot;,&quot;arial&quot;,sans-serif!important;font-size:14px' dir='auto'><tbody style='border:none;padding:0;margin:0'><tr style='border:none;margin:0px;padding:0px;height:24px'><td colspan='3' style='border:none;padding:0;margin:0;height:24px'></td></tr><tr style='border:none;margin:0px;padding:0px'><td style='border:none;padding:0;margin:0;width:24px'></td><td style='border:none;padding:0;margin:0'><p style='border:none;padding:0;margin:0;background-color:#ffffff;color:#000000;font-size:14px;font-family:&quot;helvetica&quot;,&quot;arial&quot;,sans-serif!important;font-weight:400;text-align:left'>Your password has been changed, as you asked.</p></td><td style='border:none;padding:0;margin:0;width:24px'></td></tr></tbody></table><table style='border-collapse:collapse;padding:0;width:100%;background-color:#ffffff;font-family:&quot;helvetica&quot;,&quot;arial&quot;,sans-serif!important;font-size:14px' dir='auto'><tbody style='border:none;padding:0;margin:0'><tr style='border:none;margin:0px;padding:0px;height:16px'><td colspan='3' style='border:none;padding:0;margin:0;height:16px'></td></tr><tr style='border:none;margin:0px;padding:0px'><td style='border:none;padding:0;margin:0;width:24px'></td><td style='border:none;padding:0;margin:0'><p style='border:none;padding:0;margin:0;background-color:#ffffff;color:#000000;font-size:14px;font-family:&quot;helvetica&quot;,&quot;arial&quot;,sans-serif!important;font-weight:400;text-align:left'>If you didn't ask to change your password, we're here to help keep your account secure. Visit our
<a href='https://visionizex.tech/contact.php' rel='noreferrer' target='_blank' data-saferedirecturl='https://visionizex.tech/contact.php'>Contact page</a> for more info.</p></td><td style='border:none;padding:0;margin:0;width:24px'></td></tr><tr style='border:none;margin:0px;padding:0px;height:32px'><td colspan='3' style='border:none;padding:0;margin:0;height:32px'></td></tr></tbody></table>
</div></td></tr>
</tbody></table>
</div>";

//! to send reset password OTP Email
// #otp# for otp 
$template[1] = "<div style='max-width:1200px;margin:24px auto;border:solid 1px rgba(26,28,34,0.12);background-color:#fff;font-family:SFUIText;border-radius:8px'><div style='display:flex;padding:0 24px;background-image:linear-gradient(to right, #194d42, #b07a7a);border-top-left-radius:8px;border-top-right-radius:8px'><p style='font-size:32px;font-weight:600;letter-spacing:1.2px;color:rgba(255,255,255,0.95)'>VisionizeX</p></div><div style='min-height:452px;padding:0 24px'><div><h2 style='margin-top:48px;font-size:16px;font-weight:600;line-height:1.5;letter-spacing:0.4px;color:#1a1c22'>Dear Customer</h2><p style='margin-top:16px;font-size:14px;font-weight:300;line-height:1.57;letter-spacing:0.4px;color:#1a1c22'>You are resetting login password,your verification code is:</p><code style='font-size:40px;font-family:SFPro;font-weight:bold;line-height:1.5;color:#194d42'>#otp#</code><p style='margin-top:16px;font-size:14px;font-weight:300;line-height:1.57;letter-spacing:0.4px;color:#1a1c22'>Its valid within 5 minutes. Do not tell the verification code to others.</p></div><div><h1 style='margin-top:48px;font-size:16px;font-weight:600;line-height:1.5;letter-spacing:0.4px;color:#1a1c22'>VisionizeX Team</h1><a href='https://www.visionizex.tech' style='margin-top:12px;font-size:12px;line-height:1.5;color:#2949ff;font-size:14px;letter-spacing:0.4px' rel='noreferrer' target='_blank' data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech </a></div></div></div>";


//! to send sign-up OTP Email
// #otp# for otp 
$template[2] = "<div style='max-width:1200px;margin:24px auto;border:solid 1px rgba(26,28,34,0.12);background-color:#fff;font-family:SFUIText;border-radius:8px'><div style='display:flex;padding:0 24px;background-image:linear-gradient(to right,#194d42,#b07a7a);border-top-left-radius:8px;border-top-right-radius:8px'><p style='font-size:32px;font-weight:600;letter-spacing:1.2px;color:rgba(255,255,255,0.95)'>VisionizeX</p></div><div style='min-height:452px;padding:0 24px'><div><h2 style='margin-top:48px;font-size:16px;font-weight:600;line-height:1.5;letter-spacing:0.4px;color:#1a1c22'>Dear Customer</h2><p style='margin-top:16px;font-size:14px;font-weight:300;line-height:1.57;letter-spacing:0.4px;color:#1a1c22'>
Thanks for registering VisionizeX, your verification code is:</p><code style='font-size:40px;font-family:SFPro;font-weight:bold;line-height:1.5;color:#194d42'>#otp#</code><p style='margin-top:16px;font-size:14px;font-weight:300;line-height:1.57;letter-spacing:0.4px;color:#1a1c22'>Its valid within 5 minutes. Do not tell the verification code to others.</p></div><div><h1 style='margin-top:48px;font-size:16px;font-weight:600;line-height:1.5;letter-spacing:0.4px;color:#1a1c22'>VisionizeX Team</h1><a href='https://www.visionizex.tech' style='margin-top:12px;font-size:12px;line-height:1.5;color:#2949ff;font-size:14px;letter-spacing:0.4px' rel='noreferrer' target='_blank' data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech </a></div></div></div>";


//! to send Thank you Email for sign-up
// #name# for customer name 
$template[3] = "<div style='max-width:1200px;margin:24px auto;border:solid 1px rgba(26,28,34,0.12);background-color:#fff;font-family:Roboto,RobotoDraft,Helvetica,Arial,sans-serif;border-radius:8px'>
<div style='display:flex;padding:0 24px;background-image:linear-gradient(to right, #194d42, #b07a7a);border-top-left-radius:8px;border-top-right-radius:8px'><p style='font-size:32px;font-weight:600;letter-spacing:1.2px;color:rgba(255,255,255,0.95)'>VisionizeX</p></div><div style='min-height:452px;padding:0 50px'><div><p>Dear #name#,</p><p>Thank you for creating a VisionizeX account. Please review this email in its entirety as it contains important information.</p><p><strong>Logging In</strong></p><p>You can access our Contact area at <a href='https://www.visionizex.tech' rel='noreferrer' target='_blank'data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech</a></p><p>You will need your email address and the password you chose during signup to login.</p><p><strong>Getting Support</strong></p><p>If you need any help or assistance, you can access our support resources below.</p><p>---<br>VisionizeX Team<br><a href='https://www.visionizex.tech' target='_blank' data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech</a></p><p><small>You are receiving this email because you recently created an account. If you did not do this, please contact us.</small></p></div></div>";

//! to send Email when user fill contact form (notify that we will get back to you.)
// #name# for customer name 
$template[4] = "<div style='max-width:1200px;margin:24px auto;border:solid 1px rgba(26,28,34,0.12);background-color:#fff;font-family:Roboto,RobotoDraft,Helvetica,Arial,sans-serif;border-radius:8px'>
<div style='display:flex;padding:0 24px;background-image:linear-gradient(to right, #194d42, #b07a7a);border-top-left-radius:8px;border-top-right-radius:8px'><p style='font-size:32px;font-weight:600;letter-spacing:1.2px;color:rgba(255,255,255,0.95)'>VisionizeX</p></div><div style='min-height:452px;padding:0 50px'><div><p>Dear #name#,</p><p>Thank you for Connecting with VisionizeX. Please review this email in its entirety as it contains important information.</p><p>You are getting this email because You have submitted our contact form on <a href='https://www.visionizex.tech' rel='noreferrer' target='_blank'data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech</a></p><p>Our team will contact you in short time to solve your Query. Thank You!</p><p>---<br>VisionizeX Team<br><a href='https://www.visionizex.tech' target='_blank' data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech</a></p><p><small>You are receiving this email because you recently submitted contact form. If you did not do this, please contact us.</small></p></div><table border='0' cellpadding='0' cellspacing='0' width='100%' id='m_-6091879789459434100m_-4246095622421903555templateFooter'><tbody><tr><td valign='top'><a href='https://www.visionizex.tech' rel='noreferrer' target='_blank' data-saferedirecturl='https://www.visionizex.tech'>visit our website</a><span> | </span><a href='https://visionizex.tech/login.php' rel='noreferrer' target='_blank' data-saferedirecturl='https://visionizex.tech/login.php'>log in to your account</a><span> | </span><a href='https://visionizex.tech/contact.php' rel='noreferrer' target='_blank' data-saferedirecturl='https://visionizex.tech/contact.php'>get support</a> <br>Copyright © VisionizeX, All rights reserved.</td></tr></tbody></table></div></div>";

//! Admin - send Email to admin that user filled contact form (notify that connect with customer.)
// #name# for customer name
// #login_email# for customer login email
// #filled_email# for customer email that user filled
// #message# for customer message to admin
// #datetime# for current date and time
$template[5] = "<div style='max-width:1200px;margin:24px auto;border:solid 1px rgba(26,28,34,0.12);background-color:#fff;font-family:Roboto,RobotoDraft,Helvetica,Arial,sans-serif;border-radius:8px'>
<div style='display:flex;padding:0 24px;background-image:linear-gradient(to right, #194d42, #b07a7a);border-top-left-radius:8px;border-top-right-radius:8px'>
<p style='font-size:32px;font-weight:600;letter-spacing:1.2px;color:rgba(255,255,255,0.95)'>VisionizeX</p></div><div style='min-height:452px;padding:0 50px'><div><p>Customer is Filled Contact form on VisionizeX. Please review this email in its entirety as it contains important information.</p><p>You are getting this email because customer submitted contact form on <a href='https://www.visionizex.tech' rel='noreferrer' target='_blank'data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech</a>
</p><p>Plese Connect with Customer as soon as Possible.</p><p>Customer Name : #name#</p><p>Customer login email : #login_email#</p><p>Customer filled email : #filled_email#</p><p>Customer Message : #message#</p><p>Date and Time : #datetime#</p><p>---<br>VisionizeX Team<br><a href='https://www.visionizex.tech' target='_blank' data-saferedirecturl='https://www.visionizex.tech'>https://www.visionizex.tech</a></p><p><small>You are receiving this email because Customer recently submitted contact form. please contact them.</small></p></div><table border='0' cellpadding='0' cellspacing='0' width='100%' id='m_-6091879789459434100m_-4246095622421903555templateFooter'><tbody><tr><td valign='top'><a href='https://www.visionizex.tech' rel='noreferrer' target='_blank' data-saferedirecturl='https://www.visionizex.tech'>visit our website</a><span> | </span><a href='https://visionizex.tech/login.php' rel='noreferrer' target='_blank' data-saferedirecturl='https://visionizex.tech/login.php'>log in to your account</a><span> | </span><a href='https://visionizex.tech/contact.php' rel='noreferrer' target='_blank' data-saferedirecturl='https://visionizex.tech/contact.php'>get support</a> <br>Copyright © VisionizeX, All rights reserved.</td></tr></tbody></table></div></div>";




?>